### ISSUE TITLE
A suggestion for speed up the processing 

### ISSUE THREAD

**Issue by leftthomas** [v-iashin/video_features#16]
I found that the code will only processing one video on each GPU, and used about 2.5G memory, the memory usage is slow for GPUs which have lager memory. I wonder if there is a way like `batch size` or `multithreading` processing, and full use the GPU memory, also save the time to processing the dataset.

**Comment by v-iashin** [comment]
Well, it is often not useful as the utilization is likely already 100%. Anyway, you can achieve what you want just by running the same cli command with a different set videos. However, I see your point and such customization is useful but could be difficult to implement. 

Some feature extractors support batching such as resnet.

**Comment by leftthomas** [comment]
ok, thanks, I wonder why the Conda env named 'torch_zoo' but not 'raft'  for 'RAFT', it's confusing.

**Comment by v-iashin** [comment]
It is because torch_zoo supports multiple models, not only raft. It can be confusing for i3d with the raft backend but it should be ok for the rest.

Maybe different versions of ffmpeg is the problem. Can you compare the output length with the time? Does it produce meaningful result?

you can transform your numpy array to have float32 precision by calling .float() on it. 

Please create separate issues for separate questions. So, other people could benefit.
