### ISSUE TITLE
tmp file can't be stored and len() of unsized object

### ISSUE THREAD

**Issue by HXYNODE** [v-iashin/video_features#2]
hi Vladimir, thanks for ur awesome and systemantic work !
there are three issues when i try my best to ‘corporate’ with ur project.
specifically, i just want to extract features of the msvd & msr-vtt dataset for video captioning task.
so, the pipeline kept in my mind like followings.
first, the video dataset, msvd or msr-vtt, is cut into rgb frames one-by-one.
then, the flow frames are obtained based on those rgb frames.
next, the rgb & flow frames are sent to the cnn encoder (inceptionresnetv2, i3d) and finally the features can be extracted.
back to issues, in my mind, **the rgb & flow frames will be saved at the tmp file** according to ur documention.
however, **1) the tmp file can't be seen in my workspace although i set the --keep_tmp_file parameter and run main.py file**.
besides, **2) the warning  ‘The given Numpy array is not writeable, and ...’ always displayed** as long as the main.py file runs.
the warning caused by the code 'img=torch.as_tensor(np.asarray(pic))' in transformers file. i attempt to fix it but failed.
the third problems i met is **3) the notice 'Extraction failed at: ./sample/....mp4 with error. Continuing extraction len() of unsized object' occurs after setting --on_extraction parameter. (ps: i have a single gpu device)** 
that's all. if you have any great advice on data preprocessing for video captioning task, welcome tell me.
looking forward to your reply !

**Comment by v-iashin** [comment]
Hi thanks for your issue. It is nice to know that you considered to use this project. 

I think the feature extraction fails before it is able to save anything. 

Does it work on two sample videos?

A preliminary attempt to answer your question anyway:
1) it likely happens due to an error on extraction
2) i guess it shows you a warning that something went bad already at this point. Have tried to print the content of the files your trying to save?
3) it says that for this video it failed and continues extraction. Try uncomment this lines to see the whole error and where it occurs

https://github.com/v-iashin/video_features/blob/b11c2a36c0ae882c65b3d083e340244c56fa803a/models/i3d/extract_i3d.py#L2

https://github.com/v-iashin/video_features/blob/b11c2a36c0ae882c65b3d083e340244c56fa803a/models/i3d/extract_i3d.py#L115

**Comment by HXYNODE** [comment]
thanks for ur quickly reply !
the project peformed with the sample videos provided by u.
new clues: **1) the warning has disappeared when I set --extraction_fps parameters and the tmp files are produced.**
there are two new_mp4 files transformed from the original sample videos included in the tmp file, however, not the rgb & flow frames that i need.
2) the notice 'len() of unsized object' still appears may be due to the exception occurs in the code block `for id in indices: try: ... except ...` within extract_i3d.py. 
also the notice 'Extraction failed at: ./sample~ ' displayed even though i have comment the two lines code u proposed in ur reply.

**Comment by v-iashin** [comment]
Please, make a mwe reproducing the error. It is really hard to guess what is wrong if you send only error messages.

Uncommenting those lines should not solve the problem you are having. It helps to debug them.
