### ISSUE TITLE
Use bigger R(2+1)d pre-trained on IG65M

### ISSUE THREAD

**Issue by daniel-j-h** [v-iashin/video_features#7]
Hey there, awesome project you have here :tada: 

I checked your code and seeing

https://github.com/v-iashin/video_features/blob/71a9a08d6a350a589fd275ff7f94803757573bca/models/r21d/extract_r21d.py#L9

I was wondering if you have thought about dropping this one in

https://github.com/moabitcoin/ig65m-pytorch

since the r(2+1)d 18 features are - based on experience - not the best to work with, in the r(2+1)d family.

:v:

**Comment by v-iashin** [comment]
Hi 👋 ! 

Thanks a lot for the pointer!

I am not sure if I want to drop R(2+1)D-18 RGB completely because, for now, I think it is better to have a bigger coverage rather than the SotA selection which is not sustainable in the long term. 

However, I would be absolutely happy to have IG65M with this API.

Would you like to form a PR with the IG65M implementation?

**Comment by daniel-j-h** [comment]
Hey, realistically I don't have the time to work on this in the foreseeable future. I just wanted to point you to the IG65M pytorch model since it should be a drop in replacement wrt. its api and usage :hugs:

**Comment by v-iashin** [comment]
Hi, I understand. Thanks anyway

**Comment by v-iashin** [comment]
Thanks to @ohjho now our repo supports it
