### ISSUE TITLE
Could you provide a pip requirements

### ISSUE THREAD

**Issue by WujiangXu** [v-iashin/video_features#8]
Hello, thank you for your work. I want try to use this code to extract the i3d feature and vggish feature in the BMT branch. But the environment is hard for me to build. Cause some package can not be found in the anaconda environment. So, I want to know whether you can provide a pip requirements list.

**Comment by v-iashin** [comment]
Hello. Thanks for trying out the project.

You provide too little information to understand your problem.

The reason why your conda cannot find some packages is, most likely, because you are on Windows. You might need to look for correct conda binaries yourself since the project provides is built with Linux in mind. Another option is to build a Docker. This repo provides all versions along with the package names which will guide you. Finally, you may use the Google Colab environment.

**Comment by ohjho** [comment]
@WujiangXu I used [`pipreqs`](https://github.com/bndr/pipreqs) to make an `requirements.txt` for this repo. You might want to add in `opencv-python==4.4.0.44` manually.

if you are going to use **PWCNet** you will need `cupy` as well. Installing that might be tricky, since I have multiple CUDA_versions and the doc explicitly mentioned that CUDA 11 is not supported. I installed mine like this: `CUDA_PATH=/usr/local/cuda-10.2 pip install cupy==5.1.0`. Probably best to refer to [their docs](https://docs.cupy.dev/en/latest/install.html#) though for your specific setup. Note that this cupy version is pretty old... latest version as of May 2022 is `10.4.0`.

here's the content of my `requirements.txt` excluding `cupy`:
```
numpy==1.19.2
omegaconf==2.1.2
Pillow==9.1.0
resampy==0.2.2
scipy==1.6.1
soundfile==0.10.3.post1
torch==1.11.0
torchvision==0.12.0
tqdm==4.46.0
opencv-python==4.4.0.44
```

**Comment by v-iashin** [comment]
I think this one should be fixed after we will add a docker supporting feature extraction.

**Comment by v-iashin** [comment]
I wanted to get back to this. I think it can be related to #25. Thanks for bringing this up.

Also, if you or others have this same issue, it, perhaps, can be solved with a docker environment. Recently I made a docker image that has both environments in #53 (see the [documentation](https://v-iashin.github.io/video_features/meta/docker/) as well)

**Comment by v-iashin** [comment]
I am going to close this issue for now as one could find a way to install these https://v-iashin.github.io/video_features/meta/install_conda/ with `pip`
